sim_metric: 'cosine' # choose form ['cosine', 'l2']
keep_hard: True # True for hard examples
Kmeans_with_cos_dist: True # True for using cosine similarity for kmeans clustering
emb_memory_loc: "data/embeddings/embs.npy"
text_emb_memory_loc: None
paths_memory_loc: "data/embeddings/path.npy"
sorted_clusters_file_loc: "data/sorted_clusters"
save_folder: "data/embeddings"
paths_str_type: 'U256'
embed_float_type: 'float32'
ncentroids: 50 # original 50000
dataset_size:  1000
emb_size: 512
niter: 100
seed: 1234
